# This is a basic workflow to help you get started with Actions

name: aospdtgen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Change these values if you have forked it for your own works
  GIT_USERNAME: "Lanmiemie"
  GIT_EMAIL: "fatdeadpanda@163.com"
  Branch: "main"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Configure git and Store git Credentials
      run: |
        git config --global user.name $GIT_USERNAME
        git config --global user.email $GIT_EMAIL
        git config --global credential.helper store
        echo "https://${GIT_USERNAME}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

    - name: Install Packages
      run: |
        sudo apt update
        sudo apt install python3.8 python3-pip lzma cpio aria2 tmate neofetch speedtest-cli -y
        sudo ln -sf /usr/bin/python3.8 /usr/bin/python3
        sudo ln -sf /usr/bin/python3.8 /usr/bin/python
        sudo ln -sf /usr/bin/pip3 /usr/bin/pip
        
    - name: Clone Repo
      run: |
        mkdir test
        cd test
        git clone https://github.com/SebaUbuntu/aospdtgen.git ./
        mkdir dumps
        cd dumps
        git clone https://github.com/lanmiemie/mi_lx04_dtbdumps.git ./test/dumps
        
    - name: Run the aospdtgen
      working-directory: test
      continue-on-error: false
      timeout-minutes: 240
      run: |
        pip install .
        python3 -m aospdtgen ./test/dumps
        
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - run: source ubuntu-run.sh
    - name: Setup tmate session
      timeout-minutes: 460
      uses: mxschmitt/action-tmate@master

