# This is a basic workflow to help you get started with Actions

name: aospdtgen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Change these values if you have forked it for your own works
  GIT_USERNAME: "Lanmiemie"
  GIT_EMAIL: "fatdeadpanda@163.com"
  Branch: "main"

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Configure git and Store git Credentials
      run: |
        git config --global user.name $GIT_USERNAME
        git config --global user.email $GIT_EMAIL
        git config --global credential.helper store
        echo "https://${GIT_USERNAME}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
    - name: Install Packages
      run: |
        sudo apt update
        sudo apt install python3.8 python3-pip lzma cpio aria2 tmate wget curl neofetch speedtest-cli -y
        sudo ln -sf /usr/bin/python3.8 /usr/bin/python3
        sudo ln -sf /usr/bin/python3.8 /usr/bin/python
        sudo ln -sf /usr/bin/pip3 /usr/bin/pip
        
    - name: Clone Repo
      run: |
        mkdir workspace
        cd workspace
        git clone https://github.com/vm03/payload_dumper.git ./payloaddumper
        #git clone https://github.com/sebaubuntu-python/dumpyara ./
        mkdir dumps
        cd dumps
        curl https://cdn.cnbj1.fds.api.mi-img.com/xiaoqiang/rom/lx04/payload_2.38.105_d6447.bin > ./payload.bin
        #for img in *.bin; do zip payload.zip $img;done
        #git clone https://github.com/lanmiemie/mi_lx04_dtbdumps.git ./
        
    - name: Run the Payload Dumper
      working-directory: workspace
      continue-on-error: true
      timeout-minutes: 240
      run: |
        pip install protobuf==3.19.3
        pip install six==1.16.0
        pip install bsdiff4==1.1.5
        python payloaddumper/payload_dumper.py dumps/payload.bin
        cd output
        for img in *.img; do zip payload.zip $img;done
        #python3 -m dumpyara dumps/payload.zip
        
    - name: Run the Dumpyara
      working-directory: workspace
      continue-on-error: true
      timeout-minutes: 240
      run: |
        git clone https://github.com/lanmiemie/dumpyara 
        bash dumpyara/setup.sh
        bash dumpyara/dumpyara.sh output/payload.zip
    
      
    - name: Run the Aospdtgen
      working-directory: workspace
      continue-on-error: false
      timeout-minutes: 240
      run: |
        git clone https://github.com/sebaubuntu-python/aospdtgen
        pip install ./aospdtgen
        sed -i '$a ro.product.first_api_level=27' /home/runner/work/aospdtgen/aospdtgen/workspace/dumpyara/working/payload/system/system/build.prop
        python3 -m aospdtgen /home/runner/work/aospdtgen/aospdtgen/workspace/dumpyara/working/payload
        cd /home/runner/work/aospdtgen/aospdtgen/workspace/dumpyara/working/payload
        zip -r /home/runner/work/aospdtgen/aospdtgen/workspace/dtbdumps.zip *
        cd /home/runner/work/aospdtgen/aospdtgen/workspace/output
        zip -r /home/runner/work/aospdtgen/aospdtgen/workspace/devicetree.zip *
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /home/runner/work/aospdtgen/aospdtgen/workspace/devicetree.zip
          /home/runner/work/aospdtgen/aospdtgen/workspace/dtbdumps.zip
        name: ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: Device Tree & Dtbdumps
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
      
